#!/bin/bash
set -eo pipefail
source $(dirname $0)/config/paths.sh

mkdir -p $app_dir/.profile.d
mkdir -p $env_dir
mkdir -p $cache_root
mkdir -p $buildpack_root

# Compile the slug
/build/compile.sh

## Generate start commands
cat > /start <<EOF
#!/bin/bash
export HOME=$app_dir
chown -R $user_name:$user_name $app_dir
cd $app_dir

for file in .profile.d/*.sh; do
  source \$file
done
hash -r

case "\$(basename \$0)" in
  start)
    if [[ -f Procfile ]]; then
      command="\$(ruby -e "require 'yaml';puts YAML.load_file('Procfile')['\$1']")"
    else
      command="\$(ruby -e "require 'yaml';puts (YAML.load_file('.release')['default_process_types'] || {})['\$1']")"
    fi
    ;;
  *)
    command="\$@"
    ;;
esac

setuidgid $user_name \$(eval echo \${command})
EOF

chmod +x /start
ln -nsf /start /exec

# Clean up
rm -rf /build/
rm -rf /tmp/*
